# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14
dist:
  xenial
sudo:
  required

services:
  - postgresql

before_install:
  - psql -c 'create database jarsofttest;' -U postgres
  - psql -c 'create database jarsoft;' -U postgres

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту gasevskyv@gmail.com если сборка упала
notifications:
  email:
    recipients:
      - gasevskyv@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
env:
  global:
    - CODECOV_TOKEN="ec443ad2-620f-42fa-81ff-18791b3c6898"